/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSystemSettingsRouteImport } from './routes/app.system-settings'
import { Route as AppSustainabilityRouteImport } from './routes/app.sustainability'
import { Route as AppSubmitApprovalRouteImport } from './routes/app.submit-approval'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppRiskAssessmentRouteImport } from './routes/app.risk-assessment'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProductAnalysisRouteImport } from './routes/app.product-analysis'
import { Route as AppPackagingPreviewRouteImport } from './routes/app.packaging-preview'
import { Route as AppPackagingPlannerRouteImport } from './routes/app.packaging-planner'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCostAnalysisRouteImport } from './routes/app.cost-analysis'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppApprovalsIdRouteImport } from './routes/app.approvals.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSettingsRoute = AppSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSustainabilityRoute = AppSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitApprovalRoute = AppSubmitApprovalRouteImport.update({
  id: '/submit-approval',
  path: '/submit-approval',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskAssessmentRoute = AppRiskAssessmentRouteImport.update({
  id: '/risk-assessment',
  path: '/risk-assessment',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductAnalysisRoute = AppProductAnalysisRouteImport.update({
  id: '/product-analysis',
  path: '/product-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagingPreviewRoute = AppPackagingPreviewRouteImport.update({
  id: '/packaging-preview',
  path: '/packaging-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagingPlannerRoute = AppPackagingPlannerRouteImport.update({
  id: '/packaging-planner',
  path: '/packaging-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCostAnalysisRoute = AppCostAnalysisRouteImport.update({
  id: '/cost-analysis',
  path: '/cost-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsIdRoute = AppApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppApprovalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/approvals': typeof AppApprovalsRouteWithChildren
  '/app/cost-analysis': typeof AppCostAnalysisRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/packaging-planner': typeof AppPackagingPlannerRoute
  '/app/packaging-preview': typeof AppPackagingPreviewRoute
  '/app/product-analysis': typeof AppProductAnalysisRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk-assessment': typeof AppRiskAssessmentRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submit-approval': typeof AppSubmitApprovalRoute
  '/app/sustainability': typeof AppSustainabilityRoute
  '/app/system-settings': typeof AppSystemSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/approvals/$id': typeof AppApprovalsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/approvals': typeof AppApprovalsRouteWithChildren
  '/app/cost-analysis': typeof AppCostAnalysisRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/packaging-planner': typeof AppPackagingPlannerRoute
  '/app/packaging-preview': typeof AppPackagingPreviewRoute
  '/app/product-analysis': typeof AppProductAnalysisRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk-assessment': typeof AppRiskAssessmentRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submit-approval': typeof AppSubmitApprovalRoute
  '/app/sustainability': typeof AppSustainabilityRoute
  '/app/system-settings': typeof AppSystemSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/approvals/$id': typeof AppApprovalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/approvals': typeof AppApprovalsRouteWithChildren
  '/app/cost-analysis': typeof AppCostAnalysisRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/packaging-planner': typeof AppPackagingPlannerRoute
  '/app/packaging-preview': typeof AppPackagingPreviewRoute
  '/app/product-analysis': typeof AppProductAnalysisRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk-assessment': typeof AppRiskAssessmentRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submit-approval': typeof AppSubmitApprovalRoute
  '/app/sustainability': typeof AppSustainabilityRoute
  '/app/system-settings': typeof AppSystemSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/approvals/$id': typeof AppApprovalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/approvals'
    | '/app/cost-analysis'
    | '/app/dashboard'
    | '/app/packaging-planner'
    | '/app/packaging-preview'
    | '/app/product-analysis'
    | '/app/reports'
    | '/app/risk-assessment'
    | '/app/roles'
    | '/app/settings'
    | '/app/submit-approval'
    | '/app/sustainability'
    | '/app/system-settings'
    | '/app/users'
    | '/app/'
    | '/app/approvals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/approvals'
    | '/app/cost-analysis'
    | '/app/dashboard'
    | '/app/packaging-planner'
    | '/app/packaging-preview'
    | '/app/product-analysis'
    | '/app/reports'
    | '/app/risk-assessment'
    | '/app/roles'
    | '/app/settings'
    | '/app/submit-approval'
    | '/app/sustainability'
    | '/app/system-settings'
    | '/app/users'
    | '/app'
    | '/app/approvals/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/approvals'
    | '/app/cost-analysis'
    | '/app/dashboard'
    | '/app/packaging-planner'
    | '/app/packaging-preview'
    | '/app/product-analysis'
    | '/app/reports'
    | '/app/risk-assessment'
    | '/app/roles'
    | '/app/settings'
    | '/app/submit-approval'
    | '/app/sustainability'
    | '/app/system-settings'
    | '/app/users'
    | '/app/'
    | '/app/approvals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system-settings': {
      id: '/app/system-settings'
      path: '/system-settings'
      fullPath: '/app/system-settings'
      preLoaderRoute: typeof AppSystemSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sustainability': {
      id: '/app/sustainability'
      path: '/sustainability'
      fullPath: '/app/sustainability'
      preLoaderRoute: typeof AppSustainabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submit-approval': {
      id: '/app/submit-approval'
      path: '/submit-approval'
      fullPath: '/app/submit-approval'
      preLoaderRoute: typeof AppSubmitApprovalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk-assessment': {
      id: '/app/risk-assessment'
      path: '/risk-assessment'
      fullPath: '/app/risk-assessment'
      preLoaderRoute: typeof AppRiskAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/product-analysis': {
      id: '/app/product-analysis'
      path: '/product-analysis'
      fullPath: '/app/product-analysis'
      preLoaderRoute: typeof AppProductAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packaging-preview': {
      id: '/app/packaging-preview'
      path: '/packaging-preview'
      fullPath: '/app/packaging-preview'
      preLoaderRoute: typeof AppPackagingPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packaging-planner': {
      id: '/app/packaging-planner'
      path: '/packaging-planner'
      fullPath: '/app/packaging-planner'
      preLoaderRoute: typeof AppPackagingPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cost-analysis': {
      id: '/app/cost-analysis'
      path: '/cost-analysis'
      fullPath: '/app/cost-analysis'
      preLoaderRoute: typeof AppCostAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals/$id': {
      id: '/app/approvals/$id'
      path: '/$id'
      fullPath: '/app/approvals/$id'
      preLoaderRoute: typeof AppApprovalsIdRouteImport
      parentRoute: typeof AppApprovalsRoute
    }
  }
}

interface AppApprovalsRouteChildren {
  AppApprovalsIdRoute: typeof AppApprovalsIdRoute
}

const AppApprovalsRouteChildren: AppApprovalsRouteChildren = {
  AppApprovalsIdRoute: AppApprovalsIdRoute,
}

const AppApprovalsRouteWithChildren = AppApprovalsRoute._addFileChildren(
  AppApprovalsRouteChildren,
)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRouteWithChildren
  AppCostAnalysisRoute: typeof AppCostAnalysisRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPackagingPlannerRoute: typeof AppPackagingPlannerRoute
  AppPackagingPreviewRoute: typeof AppPackagingPreviewRoute
  AppProductAnalysisRoute: typeof AppProductAnalysisRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskAssessmentRoute: typeof AppRiskAssessmentRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmitApprovalRoute: typeof AppSubmitApprovalRoute
  AppSustainabilityRoute: typeof AppSustainabilityRoute
  AppSystemSettingsRoute: typeof AppSystemSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRouteWithChildren,
  AppCostAnalysisRoute: AppCostAnalysisRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPackagingPlannerRoute: AppPackagingPlannerRoute,
  AppPackagingPreviewRoute: AppPackagingPreviewRoute,
  AppProductAnalysisRoute: AppProductAnalysisRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskAssessmentRoute: AppRiskAssessmentRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmitApprovalRoute: AppSubmitApprovalRoute,
  AppSustainabilityRoute: AppSustainabilityRoute,
  AppSystemSettingsRoute: AppSystemSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
